//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Windows.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GameResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GameResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Game.Windows.Resources.GameResource", typeof(GameResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginner.
        /// </summary>
        internal static string Beginner {
            get {
                return ResourceManager.GetString("Beginner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard Worker.
        /// </summary>
        internal static string HardWorker {
            get {
                return ResourceManager.GetString("HardWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Star.
        /// </summary>
        internal static string LocalStar {
            get {
                return ResourceManager.GetString("LocalStar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Idol.
        /// </summary>
        internal static string NationalIdol {
            get {
                return ResourceManager.GetString("NationalIdol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promissing.
        /// </summary>
        internal static string Promissing {
            get {
                return ResourceManager.GetString("Promissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worldwide Star.
        /// </summary>
        internal static string WorldwideStar {
            get {
                return ResourceManager.GetString("WorldwideStar", resourceCulture);
            }
        }
    }
}
